@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.token}}

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "vittorfranceschi04@gmail.com",
    "password": "Password123@"
}

### Auth register
# @name createUser
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "vittorfranceschi04@gmail.com",
    "password": "Password123@",
    "name": "Vittor"
}

# ADMIN ########################################################################

### Admin register
# @name createUserAdmin
POST {{baseUrl}}/admin/users
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "email": "vittorfra@gmail.com",
    "password": "Password123@",
    "name": "Vittor"
}