@baseUrl = http://localhost:3001
@jwtToken = {{authLogin.response.body.token}}

# STORE ########################################################################

### Read One Product
# @name readOneProduct
GET {{baseUrl}}/store/products/4daba48b-8c0d-443c-bbf9-e40eecf72c30
Content-Type: application/json

### Read All Products
# @name readProducts
GET {{baseUrl}}/store/products/
Content-Type: application/json

### Read All Categories
# @name readCategories
GET {{baseUrl}}/store/categories/
Content-Type: application/json

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "vittorfranceschi@gmail.com",
    "password": "Password123@"
}

### Auth register
# @name createUser
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "vittorfranceschi@gmail.com",
    "password": "Password123@",
    "name": "Vittor"
}

### Auth  me
# @name authMe
GET {{baseUrl}}/auth/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


# ADMIN ########################################################################

### Admin register
# @name createUserAdmin
POST {{baseUrl}}/admin/users
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "email": "admi@gmail.com",
    "password": "Password123@",
    "name": "Admin"
}

### Upload Image
# @name uploadImage
POST {{baseUrl}}/admin/upload/image
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.jgp"
Content-Type: image/jpg

< ./teste.jpg
------BryenFormBoundary--

### Create Product
# @name createProduct
POST {{baseUrl}}/admin/products
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Blonde",
    "description": "a perfect album by frank ocean",
    "price": 100,
    "stock": 100,
    "imageUrl": "https://res.cloudinary.com/devll4edo/image/upload/v1762823224/nest-ecommerce/kjujinmuhfm1qxfeubst.jpg",
    "imageId": "nest-ecommerce/kjujinmuhfm1qxfeubst",
    "categoryId": "9ea66251-0673-4933-bb0b-f0def672f4b3"
}

### Update Product
# @name updateProduct
PATCH {{baseUrl}}/admin/products/e44ec94d-645c-403d-a050-2aa0ef26e222
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Blond",
    "stock": 50
}

### Delete Product
# @name deleteProduct
DELETE {{baseUrl}}/admin/products/1effb590-3e03-49a7-a8a3-bf51e1d1d74f
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Create Category
# @name createCategory
POST {{baseUrl}}/admin/categories
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "R&B",
    "slug": "R&B"
}

### Update Category
# @name updateCategory
PATCH {{baseUrl}}/admin/categories/a4c8b07e-3264-4418-aeb0-4d8308751ffb
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "R&B",
    "slug": "R&B"
}

### Delete Category
# @name deleteCategory
DELETE {{baseUrl}}/admin/categories/42737ca9-696c-4b78-8a56-15765a5a8a6f
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Read All Orders
# @name readAllOrders

GET {{baseUrl}}/admin/orders
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

# ACCOUNT ########################################################################

### Create Cart Item
# @name createCartItem
POST {{baseUrl}}/account/cart/items/
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "productId": "e44ec94d-645c-403d-a050-2aa0ef26e222",
    "quantity": 1
}

### Read Cart Items
# @name readCartItems
GET {{baseUrl}}/account/cart
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Delete cart item
# @name deleteCartItem
DELETE {{baseUrl}}/account/cart/items/eca931d9-2ec9-4f78-87f5-9a5e663f4c91
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Update cart item
# @name updateCartItem
PATCH {{baseUrl}}/account/cart/items/eca931d9-2ec9-4f78-87f5-9a5e663f4c91
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "quantity": 99
}

### Checkout
# @name checkout
POST {{baseUrl}}/account/checkout
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "shippingAddress": {
        "city": "Araruama"
    }
}

### Read Orders
# @name readOrders
GET {{baseUrl}}/account/orders
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

### Read One Order
# @name readOneOrder
GET {{baseUrl}}/account/orders/05065f78-56be-4c1a-8413-fc99317cb535
Content-Type: application/json
Authorization: Bearer {{jwtToken}}


