@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.token}}

# STORE ########################################################################

### Read One Product
# @name readOneProduct
GET {{baseUrl}}/store/products/4daba48b-8c0d-443c-bbf9-e40eecf72c30
Content-Type: application/json

### Read All Products
# @name readProducts
GET {{baseUrl}}/store/products/?sortBy=price&sortOrder=DESC&page=1
Content-Type: application/json

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "vittorfranceschi@gmail.com",
    "password": "Password123@"
}

### Auth register
# @name createUser
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "vittorfranceschi@gmail.com",
    "password": "Password123@",
    "name": "Vittor"
}

# ADMIN ########################################################################

### Admin register
# @name createUserAdmin
POST {{baseUrl}}/admin/users
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "email": "admi@gmail.com",
    "password": "Password123@",
    "name": "Admin"
}

### Create Product
# @name createProduct
POST {{baseUrl}}/admin/products
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Blonde",
    "description": "a perfect album",
    "price": "1.99",
    "stock": 100,
    "imageUrl": "http://localhost:3000",
    "categoryId": "a4c8b07e-3264-4418-aeb0-4d8308751ffb"
}